// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-spec-data.mjs from spec/data. Do not edit this file.

import type { Precision, PrecisionThreshold, SegmentBounds, SegmentRule } from './types.js';

/**
 * State codes and names, from spec/data/states.json.
 *
 * @internal
 */
export const STATES: ReadonlyMap<string, string> = new Map([
  ['AB', 'Abia'],
  ['AD', 'Adamawa'],
  ['AK', 'Akwa Ibom'],
  ['AN', 'Anambra'],
  ['BA', 'Bauchi'],
  ['BE', 'Benue'],
  ['BO', 'Borno'],
  ['BY', 'Bayelsa'],
  ['CR', 'Cross River'],
  ['DE', 'Delta'],
  ['EB', 'Ebonyi'],
  ['ED', 'Edo'],
  ['EK', 'Ekiti'],
  ['EN', 'Enugu'],
  ['FC', 'Federal Capital Territory'],
  ['GO', 'Gombe'],
  ['IM', 'Imo'],
  ['JI', 'Jigawa'],
  ['KD', 'Kaduna'],
  ['KE', 'Kebbi'],
  ['KN', 'Kano'],
  ['KO', 'Kogi'],
  ['KT', 'Katsina'],
  ['KW', 'Kwara'],
  ['LA', 'Lagos'],
  ['NA', 'Nasarawa'],
  ['NI', 'Niger'],
  ['OG', 'Ogun'],
  ['ON', 'Ondo'],
  ['OS', 'Osun'],
  ['OY', 'Oyo'],
  ['PL', 'Plateau'],
  ['RI', 'Rivers'],
  ['SO', 'Sokoto'],
  ['TA', 'Taraba'],
  ['YO', 'Yobe'],
  ['ZA', 'Zamfara'],
]);

/**
 * Segment names from the least to the most precise.
 *
 * @internal
 */
export const PRECISION_ORDER: readonly Precision[] = ['state', 'lga', 'district', 'area', 'unit'];

/**
 * The rule for each segment, in order.
 *
 * @internal
 */
export const SEGMENT_RULES: readonly SegmentRule[] = [
  { name: 'state', length: 2, characters: 'letters', minimum: null },
  { name: 'lga', length: 2, characters: 'digits', minimum: 1 },
  { name: 'district', length: 3, characters: 'letters-or-digits', minimum: null },
  { name: 'area', length: 2, characters: 'letters', minimum: null },
  { name: 'unit', length: 2, characters: 'digits', minimum: 1 },
];

/**
 * Where each segment starts and ends in a compact code.
 *
 * @internal
 */
export const SEGMENT_BOUNDS: Readonly<Record<Precision, SegmentBounds>> = {
  state: { start: 0, end: 2 },
  lga: { start: 2, end: 4 },
  district: { start: 4, end: 7 },
  area: { start: 7, end: 9 },
  unit: { start: 9, end: 11 },
};

/**
 * GPS accuracy limits, from spec/data/precision.json.
 *
 * @internal
 */
export const PRECISION_THRESHOLDS: readonly PrecisionThreshold[] = [
  { maxAccuracyM: 8, precision: 'unit' },
  { maxAccuracyM: 20, precision: 'area' },
  { maxAccuracyM: 50, precision: 'district' },
];

/**
 * The precision for an accuracy above every limit.
 *
 * @internal
 */
export const PRECISION_FALLBACK: Precision = 'lga';

/**
 * The most code points that parse reads. Longer input fails before normalize runs.
 *
 * @internal
 */
export const MAX_INPUT_CODE_POINTS: number = 64;

/**
 * Characters that normalize removes. Use it only with replace, because of flag g.
 *
 * @internal
 */
export const SEPARATORS: RegExp = /[\u{0009}\u{000A}\u{000B}\u{000C}\u{000D}\u{0020}\u{002D}\u{002E}\u{0085}\u{00A0}\u{00AD}\u{1680}\u{2000}\u{2001}\u{2002}\u{2003}\u{2004}\u{2005}\u{2006}\u{2007}\u{2008}\u{2009}\u{200A}\u{200B}\u{200C}\u{200D}\u{200E}\u{200F}\u{2010}\u{2011}\u{2012}\u{2013}\u{2014}\u{2015}\u{2028}\u{2029}\u{202F}\u{205F}\u{2060}\u{2212}\u{3000}\u{FEFF}]/gu;

/**
 * Old 6-digit NIPOST postcodes.
 *
 * @internal
 */
export const LEGACY: RegExp = /^[0-9]{6}$/u;

/**
 * Typo fixes in digit segments.
 *
 * @internal
 */
export const DIGIT_FIXES: ReadonlyMap<string, string> = new Map([
  ['O', '0'],
  ['I', '1'],
  ['L', '1'],
]);

/**
 * Typo fixes in letter segments.
 *
 * @internal
 */
export const LETTER_FIXES: ReadonlyMap<string, string> = new Map([
  ['0', 'O'],
  ['1', 'I'],
]);
