// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-spec-data.mjs from spec/data. Do not edit this file.

import type { Precision, PrecisionThreshold, SegmentBounds, SegmentRule } from './types.js';

/**
 * State codes and names, from spec/data/states.json.
 *
 * @internal
 */
export const STATES: ReadonlyMap<string, string> = new Map([
  ['AB', 'Abia'],
  ['AD', 'Adamawa'],
  ['AK', 'Akwa Ibom'],
  ['AN', 'Anambra'],
  ['BA', 'Bauchi'],
  ['BE', 'Benue'],
  ['BO', 'Borno'],
  ['BY', 'Bayelsa'],
  ['CR', 'Cross River'],
  ['DE', 'Delta'],
  ['EB', 'Ebonyi'],
  ['ED', 'Edo'],
  ['EK', 'Ekiti'],
  ['EN', 'Enugu'],
  ['FC', 'Federal Capital Territory'],
  ['GO', 'Gombe'],
  ['IM', 'Imo'],
  ['JI', 'Jigawa'],
  ['KD', 'Kaduna'],
  ['KE', 'Kebbi'],
  ['KN', 'Kano'],
  ['KO', 'Kogi'],
  ['KT', 'Katsina'],
  ['KW', 'Kwara'],
  ['LA', 'Lagos'],
  ['NA', 'Nasarawa'],
  ['NI', 'Niger'],
  ['OG', 'Ogun'],
  ['ON', 'Ondo'],
  ['OS', 'Osun'],
  ['OY', 'Oyo'],
  ['PL', 'Plateau'],
  ['RI', 'Rivers'],
  ['SO', 'Sokoto'],
  ['TA', 'Taraba'],
  ['YO', 'Yobe'],
  ['ZA', 'Zamfara'],
]);

/**
 * Segment names from the least to the most precise.
 *
 * @internal
 */
export const PRECISION_ORDER: readonly Precision[] = ['state', 'lga', 'district', 'area', 'unit'];

/**
 * The rule for each segment, in order.
 *
 * @internal
 */
export const SEGMENT_RULES: readonly SegmentRule[] = [
  { name: 'state', length: 2, characters: 'letters', minimum: null },
  { name: 'lga', length: 2, characters: 'digits', minimum: 1 },
  { name: 'district', length: 3, characters: 'letters-or-digits', minimum: null },
  { name: 'area', length: 2, characters: 'letters', minimum: null },
  { name: 'unit', length: 2, characters: 'digits', minimum: 1 },
];

/**
 * Where each segment starts and ends in a compact code.
 *
 * @internal
 */
export const SEGMENT_BOUNDS: Readonly<Record<Precision, SegmentBounds>> = {
  state: { start: 0, end: 2 },
  lga: { start: 2, end: 4 },
  district: { start: 4, end: 7 },
  area: { start: 7, end: 9 },
  unit: { start: 9, end: 11 },
};

/**
 * GPS accuracy limits, from spec/data/precision.json.
 *
 * @internal
 */
export const PRECISION_THRESHOLDS: readonly PrecisionThreshold[] = [
  { maxAccuracyM: 8, precision: 'unit' },
  { maxAccuracyM: 20, precision: 'area' },
  { maxAccuracyM: 50, precision: 'district' },
];

/**
 * The precision for an accuracy above every limit.
 *
 * @internal
 */
export const PRECISION_FALLBACK: Precision = 'lga';

/**
 * Characters that normalize removes. Use it only with replace, because of flag g.
 *
 * @internal
 */
export const SEPARATORS: RegExp = /[\u0009\u000A\u000B\u000C\u000D\u0020\u002D\u002E\u0085\u00A0\u00AD\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u200B\u200C\u200D\u200E\u200F\u2010\u2011\u2012\u2013\u2014\u2015\u2028\u2029\u202F\u205F\u2060\u2212\u3000\uFEFF]/gu;

/**
 * Old 6-digit NIPOST postcodes.
 *
 * @internal
 */
export const LEGACY: RegExp = /^[0-9]{6}$/u;

/**
 * Typo fixes in digit segments.
 *
 * @internal
 */
export const DIGIT_FIXES: ReadonlyMap<string, string> = new Map([
  ['O', '0'],
  ['I', '1'],
  ['L', '1'],
]);

/**
 * Typo fixes in letter segments.
 *
 * @internal
 */
export const LETTER_FIXES: ReadonlyMap<string, string> = new Map([
  ['0', 'O'],
  ['1', 'I'],
]);
