// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import process from 'node:process';
import { after, describe, it } from 'node:test';
import { fileURLToPath, URL } from 'node:url';

const SCRIPT = fileURLToPath(new URL('./generate-messages.mjs', import.meta.url));
const CATALOGUE = fileURLToPath(new URL('../spec/messages/field_en.arb', import.meta.url));
const NOT_GENERATED = '// This is not the generated file.\n';

const folders = [];

after(() => {
  for (const folder of folders) {
    rmSync(folder, { recursive: true, force: true });
  }
});

// A copy of the script, the catalogue and the folder of the generated file. `change` edits the
// parsed catalogue in the copy.
function copyOfRepo(change = () => undefined) {
  const root = mkdtempSync(join(tmpdir(), 'generate-messages-'));
  folders.push(root);
  mkdirSync(join(root, 'scripts'));
  mkdirSync(join(root, 'spec', 'messages'), { recursive: true });
  mkdirSync(join(root, 'packages', 'field', 'src'), { recursive: true });
  copyFileSync(SCRIPT, join(root, 'scripts', 'generate-messages.mjs'));
  const catalogue = JSON.parse(readFileSync(CATALOGUE, 'utf8'));
  change(catalogue);
  writeFileSync(join(root, 'spec', 'messages', 'field_en.arb'), JSON.stringify(catalogue));
  return root;
}

function generatedFile(root) {
  return join(root, 'packages', 'field', 'src', 'spec-messages.ts');
}

function generate(root, ...args) {
  const script = join(root, 'scripts', 'generate-messages.mjs');
  const { status, stdout, stderr } = spawnSync(process.execPath, [script, ...args], {
    encoding: 'utf8',
  });
  return { status, stdout, stderr };
}

describe('generate-messages.mjs', () => {
  it('writes a file that --check accepts, and --check does not change it', () => {
    const root = copyOfRepo();
    assert.deepEqual(generate(root), { status: 0, stdout: '', stderr: '' });
    const text = readFileSync(generatedFile(root), 'utf8');
    assert.match(text, /@generated by scripts\/generate-messages\.mjs from spec\/messages\./);
    assert.ok(text.includes("  label: 'Postcode',"));
    assert.deepEqual(generate(root, '--check'), { status: 0, stdout: '', stderr: '' });
    assert.equal(readFileSync(generatedFile(root), 'utf8'), text);
  });

  it('writes each key once in the union of keys, in the order of the catalogue', () => {
    const root = copyOfRepo();
    generate(root);
    const text = readFileSync(generatedFile(root), 'utf8');
    assert.ok(text.includes("export type MessageKey =\n  | 'label'\n  | 'hint'\n"));
  });

  it('writes a character outside ASCII as an escape, so the file passes TELL-14', () => {
    const eAcute = String.fromCodePoint(0xe9);
    const root = copyOfRepo((catalogue) => {
      catalogue.label = `Caf${eAcute}`;
    });
    generate(root);
    const text = readFileSync(generatedFile(root), 'utf8');
    assert.ok(text.includes(`  label: 'Caf${String.fromCharCode(0x5c)}u00e9',`));
    assert.ok(!text.includes(eAcute));
  });

  it('fails with --check when the catalogue changed, and leaves the file as it was', () => {
    const root = copyOfRepo();
    writeFileSync(generatedFile(root), NOT_GENERATED);
    const checked = generate(root, '--check');
    assert.equal(checked.status, 1);
    assert.equal(
      checked.stderr,
      'packages/field/src/spec-messages.ts is out of date. Run pnpm generate.\n',
    );
    assert.equal(readFileSync(generatedFile(root), 'utf8'), NOT_GENERATED);
  });

  for (const [key, text, problem] of [
    ['Label', 'Postcode', 'The key "Label" is not lower case with underscores.'],
    ['label', 7, 'The message "label" is not text.'],
  ]) {
    it(`rejects ${problem} and writes nothing`, () => {
      const root = copyOfRepo((catalogue) => {
        delete catalogue.label;
        catalogue[key] = text;
      });
      writeFileSync(generatedFile(root), NOT_GENERATED);
      const { status, stderr } = generate(root);
      assert.equal(status, 1);
      assert.equal(stderr, `${problem}\n`);
      assert.equal(readFileSync(generatedFile(root), 'utf8'), NOT_GENERATED);
    });
  }

  it('escapes a quote and a backslash, and writes a character above U+FFFF as two escapes', () => {
    const slash = String.fromCharCode(0x5c);
    const root = copyOfRepo((catalogue) => {
      catalogue.label = `a'b${slash}c${String.fromCodePoint(0x1f600)}`;
    });
    generate(root);
    const text = readFileSync(generatedFile(root), 'utf8');
    const expected = `  label: 'a${slash}'b${slash}${slash}c${slash}ud83d${slash}ude00',`;
    assert.ok(text.includes(expected), text);
  });

  it('rejects a catalogue with no message and writes nothing', () => {
    const root = copyOfRepo((catalogue) => {
      for (const key of Object.keys(catalogue)) {
        if (!key.startsWith('@')) {
          Reflect.deleteProperty(catalogue, key);
        }
      }
    });
    writeFileSync(generatedFile(root), NOT_GENERATED);
    const { status, stderr } = generate(root);
    assert.equal(status, 1);
    assert.equal(stderr, 'The catalogue has no message.\n');
    assert.equal(readFileSync(generatedFile(root), 'utf8'), NOT_GENERATED);
  });

  it('says that the file is out of date with --check when the file is missing', () => {
    const { status, stderr } = generate(copyOfRepo(), '--check');
    assert.equal(status, 1);
    assert.equal(
      stderr,
      'packages/field/src/spec-messages.ts is out of date. Run pnpm generate.\n',
    );
  });

  it('rejects an unknown argument with exit code 2', () => {
    const { status, stderr } = generate(copyOfRepo(), '--chek');
    assert.equal(status, 2);
    assert.equal(stderr, 'Unknown argument --chek. Use --check or no argument.\n');
  });
});
