// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import process from 'node:process';
import { after, describe, it } from 'node:test';
import { fileURLToPath, URL } from 'node:url';

const SCRIPT = fileURLToPath(new URL('./generate-spec-data.mjs', import.meta.url));
const SPEC_DATA = fileURLToPath(new URL('../spec/data/', import.meta.url));
const DATA_FILES = ['states.json', 'precision.json', 'format.json'];
const NOT_GENERATED = '// This is not the generated file.\n';

const folders = [];

after(() => {
  for (const folder of folders) {
    rmSync(folder, { recursive: true, force: true });
  }
});

function editData(root, name, change) {
  const file = join(root, 'spec', 'data', name);
  const data = JSON.parse(readFileSync(file, 'utf8'));
  change(data);
  writeFileSync(file, JSON.stringify(data));
}

// A copy of the folders that the script reads and writes: the script itself, the spec data and
// the folder of the generated file. The script finds them from its own location. `edits` maps a
// data file name to a function that changes the parsed data in the copy.
function copyOfRepo(edits = {}) {
  const root = mkdtempSync(join(tmpdir(), 'generate-spec-data-'));
  folders.push(root);
  mkdirSync(join(root, 'scripts'));
  mkdirSync(join(root, 'spec', 'data'), { recursive: true });
  mkdirSync(join(root, 'packages', 'core', 'src'), { recursive: true });
  copyFileSync(SCRIPT, join(root, 'scripts', 'generate-spec-data.mjs'));
  for (const name of DATA_FILES) {
    copyFileSync(join(SPEC_DATA, name), join(root, 'spec', 'data', name));
    if (edits[name] !== undefined) {
      editData(root, name, edits[name]);
    }
  }
  return root;
}

function generatedFile(root) {
  return join(root, 'packages', 'core', 'src', 'spec-data.ts');
}

function generate(root, ...args) {
  const script = join(root, 'scripts', 'generate-spec-data.mjs');
  const { status, stdout, stderr } = spawnSync(process.execPath, [script, ...args], {
    encoding: 'utf8',
  });
  return { status, stdout, stderr };
}

// Puts another file in place of the generated file, so that a run that writes shows at once.
function placeNotGenerated(root) {
  writeFileSync(generatedFile(root), NOT_GENERATED);
}

function assertNothingWritten(root) {
  assert.equal(readFileSync(generatedFile(root), 'utf8'), NOT_GENERATED);
}

// The braced escape that the script writes for a code point. A typed backslash and u would
// reach this file as the character itself in some agent tools.
function bracedEscape(hex) {
  return `${String.fromCharCode(0x5c)}u{${hex}}`;
}

describe('generate-spec-data.mjs with good data', () => {
  it('writes a file that --check accepts, and --check does not change it', () => {
    const root = copyOfRepo();
    assert.deepEqual(generate(root), { status: 0, stdout: '', stderr: '' });
    const text = readFileSync(generatedFile(root), 'utf8');
    assert.match(text, /@generated by scripts\/generate-spec-data\.mjs from spec\/data\./);
    assert.deepEqual(generate(root, '--check'), { status: 0, stdout: '', stderr: '' });
    assert.equal(readFileSync(generatedFile(root), 'utf8'), text);
  });

  it('accepts U+10FFFF as the highest separator and 1 as the lowest input limit', () => {
    const root = copyOfRepo({
      'format.json': (format) => {
        format.separators.push('U+10FFFF');
        format.maxInputCodePoints = 1;
      },
    });
    assert.equal(generate(root).status, 0);
    const text = readFileSync(generatedFile(root), 'utf8');
    assert.ok(text.includes(bracedEscape('10FFFF')));
    assert.ok(text.includes('MAX_INPUT_CODE_POINTS: number = 1;'));
  });
});

describe('generate-spec-data.mjs --check', () => {
  it('fails when the data changed after the last write, and leaves the file as it was', () => {
    const root = copyOfRepo();
    generate(root);
    const written = readFileSync(generatedFile(root), 'utf8');
    editData(root, 'format.json', (format) => {
      format.maxInputCodePoints += 1;
    });
    const checked = generate(root, '--check');
    assert.equal(checked.status, 1);
    assert.equal(checked.stdout, '');
    assert.equal(
      checked.stderr,
      'packages/core/src/spec-data.ts is out of date. Run pnpm generate.\n',
    );
    assert.equal(readFileSync(generatedFile(root), 'utf8'), written);
  });

  it('fails on another file in place of the generated file, and leaves it as it was', () => {
    const root = copyOfRepo();
    placeNotGenerated(root);
    const checked = generate(root, '--check');
    assert.equal(checked.status, 1);
    assert.match(checked.stderr, /spec-data\.ts is out of date\. Run pnpm generate\./);
    assertNothingWritten(root);
  });
});

describe('generate-spec-data.mjs with a bad argument', () => {
  for (const args of [['--chek'], ['--check', '--write'], ['check']]) {
    it(`rejects ${args.join(' ')} with exit code 2 and writes nothing`, () => {
      const root = copyOfRepo();
      placeNotGenerated(root);
      const result = generate(root, ...args);
      assert.equal(result.status, 2);
      assert.match(result.stderr, /^Unknown argument \S+\. Use --check or no argument\.\n$/);
      assertNothingWritten(root);
    });
  }
});

describe('generate-spec-data.mjs with a bad data version', () => {
  for (const name of DATA_FILES) {
    for (const version of [2, undefined]) {
      it(`rejects the version ${String(version)} in ${name} and writes nothing`, () => {
        const root = copyOfRepo({
          [name]: (data) => {
            data.version = version;
          },
        });
        placeNotGenerated(root);
        const result = generate(root);
        assert.equal(result.status, 1);
        const message = `spec/data/${name} has version ${String(version)}, not 1.`;
        assert.ok(result.stderr.includes(message), result.stderr);
        assertNothingWritten(root);
      });
    }
  }
});

describe('generate-spec-data.mjs with a bad separator label', () => {
  const badLabels = [
    { label: 'U+110000', shown: '"U+110000"' },
    { label: 'U+FFFFFF', shown: '"U+FFFFFF"' },
    { label: ['U+2013'], shown: '["U+2013"]' },
    { label: 8211, shown: '8211' },
    { label: null, shown: 'null' },
    { label: 'u+2013', shown: '"u+2013"' },
    { label: 'U+201', shown: '"U+201"' },
    { label: 'U+0002013', shown: '"U+0002013"' },
  ];

  for (const { label, shown } of badLabels) {
    it(`rejects the label ${shown} and names it`, () => {
      const root = copyOfRepo({
        'format.json': (format) => {
          format.separators.splice(1, 0, label);
        },
      });
      placeNotGenerated(root);
      const result = generate(root);
      assert.equal(result.status, 1);
      assert.ok(result.stderr.includes(`Bad separator label ${shown}.`), result.stderr);
      assertNothingWritten(root);
    });
  }
});

describe('generate-spec-data.mjs with a bad maxInputCodePoints', () => {
  const badLimits = [
    { limit: 0, shown: '0' },
    { limit: -1, shown: '-1' },
    { limit: 1.5, shown: '1.5' },
    { limit: 1e21, shown: '1e+21' },
    { limit: '64', shown: '"64"' },
    { limit: null, shown: 'null' },
    { limit: undefined, shown: 'undefined' },
  ];

  for (const { limit, shown } of badLimits) {
    it(`rejects ${shown} and names it`, () => {
      const root = copyOfRepo({
        'format.json': (format) => {
          format.maxInputCodePoints = limit;
        },
      });
      placeNotGenerated(root);
      const result = generate(root);
      assert.equal(result.status, 1);
      const message = `maxInputCodePoints ${shown}. Use a positive whole number.`;
      assert.ok(result.stderr.includes(message), result.stderr);
      assertNothingWritten(root);
    });
  }
});
