// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-messages.mjs from spec/messages. Do not edit this file.

/**
 * The key of each message that the field shows. `spec/field.md` says when each one shows.
 */
export type MessageKey =
  | 'label'
  | 'hint'
  | 'empty'
  | 'bad_character'
  | 'bad_length'
  | 'unknown_state'
  | 'bad_lga'
  | 'bad_area'
  | 'bad_unit'
  | 'suggestion'
  | 'use_suggestion'
  | 'legacy_accepted'
  | 'legacy_rejected'
  | 'valid'
  | 'checking'
  | 'not_found'
  | 'confirmed'
  | 'confirmed_place'
  | 'check_failed'
  | 'secret_key'
  | 'use_location'
  | 'locating'
  | 'gps_coarse'
  | 'gps_not_found'
  | 'gps_denied'
  | 'gps_unavailable';

/**
 * The text of the field in one language, one message for each key. A name in braces, such
 * as `{count}`, is a placeholder that the field fills in.
 */
export type Messages = Readonly<Record<MessageKey, string>>;

/**
 * The British English messages of the spec.
 *
 * @internal
 */
export const ENGLISH: Messages = {
  label: 'Postcode',
  hint: '11 letters and numbers, for example EK 01 A03 FK 01',
  empty: 'Enter your postcode.',
  bad_character: 'Use only letters and numbers.',
  bad_length: 'A postcode has 11 letters and numbers. You entered {count}.',
  unknown_state: 'The first part must be a state code, such as LA or FC.',
  bad_lga: 'The second part must be a number from 01 to 99.',
  bad_area: 'The fourth part must be 2 letters.',
  bad_unit: 'The last part must be a number from 01 to 99.',
  suggestion: 'Did you mean {postcode}?',
  use_suggestion: 'Use this postcode',
  legacy_accepted: 'This is an old 6-digit postcode. If you know your new one, enter it instead.',
  legacy_rejected: 'This is an old 6-digit postcode. Enter a new one, such as EK 01 A03 FK 01.',
  valid: 'This postcode is in {state}.',
  checking: 'Checking your postcode.',
  not_found: 'We could not find this postcode. Check each part, or continue if you are sure.',
  confirmed: 'We found this postcode in {state}.',
  confirmed_place: 'We found this postcode: {locality}, {lga}, {state}.',
  check_failed: 'We could not check this postcode just now. You can still continue.',
  secret_key: 'We cannot check postcodes on this page. You can still continue.',
  use_location: 'Use my location',
  locating: 'Finding your location.',
  gps_coarse: 'We added part of your postcode from your location. Type the rest.',
  gps_not_found: 'We found no postcode at your location. Type your postcode.',
  gps_denied: 'We cannot use your location. Type your postcode.',
  gps_unavailable: 'We could not find your location. Type your postcode.',
};
